name: Dynamic Uses
description: Dynamically resolve and use another GitHub action. Workaround for https://github.com/actions/runner/issues/895
author: Jon Jensen
inputs:
  uses:
    description: Action reference or path, e.g. `actions/setup-node@v3`
    required: true
  with:
    description: 'YAML/JSON string of `inputs` for the action, e.g. `node-version: 18` or `{"node-version": "18"}`'
    required: false
    default: "{}"
  env-outputs:
    description: "Whether to set an environment variable for each of the action's outputs. Defaults to `false`."
    required: false
  env-outputs-prefix:
    description: "Prefix to use for the output environment variable names. Implies `env-outputs: true`"
    required: false
  env-outputs-upcase:
    description: "Whether to capitalize environment variable names. Default to `false`. Implies `env-outputs: true` if set explicitly"
    required: false
  env-outputs-onconflict:
    description: "Error handling behavior when an output environment variable conflicts with an existing variable of the same name. Defaults to `overwrite`. Possible values are: `overwrite`, `preserve`, `error`. Implies `env-outputs: true` if set explicitly"
    required: false
outputs:
  outputs:
    description: 'JSON-ified `outputs` from the action, e.g. `{"node-version": "v18.12.0", "cache-hit": true}`'
    value: ${{ steps.run.outputs.outputs }}
runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      env:
        uses: ${{ inputs.uses }}
        with: ${{ inputs.with }}
        # inject the outputs value expression via env so that we can avoid
        # GHA+shell escaping complications 😅
        outputs: ${{ '${{ toJSON(steps.run.outputs) }}' }}
      run: |
        mkdir -p ./.tmp-dynamic-uses &&
        cat <<DYNAMIC_USES_EOF >./.tmp-dynamic-uses/action.yml
        outputs:
          outputs:
            value: $outputs
        runs:
          using: composite
          steps:
          - run: rm -rf ./.tmp-dynamic-uses
            shell: bash
          - name: Run
            id: run
            uses: '$(echo "$uses" | sed "s/'/''/g")'
            with:
        $(echo "$with" | sed -E "s/^/      /; s/\\\$\\{\\{/\${{'$'}}{{'\$'}}{{/g")
        DYNAMIC_USES_EOF
    - name: Run
      id: run
      uses: ./.tmp-dynamic-uses
    - name: Set output environment variables
      if: inputs.env-outputs != 'false' && (inputs.env-outputs || inputs.env-outputs-prefix || inputs.env-outputs-upcase || inputs.env-outputs-onconflict)
      env:
        step_outputs: ${{ steps.run.outputs.outputs }}
        env_outputs_prefix: ${{ inputs.env-outputs-prefix }}
        env_outputs_upcase: ${{ inputs.env-outputs-upcase == 'true' }}
        env_outputs_onconflict: ${{ inputs.env-outputs-onconflict || 'overwrite' }}
      shell: bash
      run: |
        if ! [[ "$env_outputs_onconflict" =~ ^(overwrite|preserve|error)$ ]]; then
          echo "::error::Invalid env-outputs-onconflict value: '$env_outputs_onconflict'. Expected 'overwrite', 'preserve', or 'error'."
          exit 1
        fi
        for key in $(echo "$step_outputs" | jq -r 'keys[]'); do
          value="$(echo "$step_outputs" | jq -r --arg key "$key" '.[$key]')"
          if [[ -n "$env_outputs_prefix" ]]; then
            key="${env_outputs_prefix}${key}"
          fi
          if [[ "$env_outputs_upcase" == "true" ]]; then
            key="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
          else
            key="$(echo "$key" | tr '[:upper:]' '[:lower:]')"
          fi
          key="$(echo "$key" | sed -E 's/[^a-zA-Z0-9_]/_/g')"
          if printenv "$key" &>/dev/null; then
            if [[ "$env_outputs_onconflict" == "overwrite" ]]; then
              echo "::warning::Environment variable '$key' already exists, overwriting with value from action output"
            elif [[ "$env_outputs_onconflict" == "preserve" ]]; then
              echo "::warning::Environment variable '$key' already exists, preserving existing value"
              continue
            else
              echo "::error::Environment variable '$key' already exists, and env-outputs-onconflict is set to 'error'"
              exit 1
            fi
          fi
          echo "exporting $key=$value"
          {
            echo "$key<<__DYNAMIC_USES_ENV_OUTPUT_EOF"
            echo "$value"
            echo "__DYNAMIC_USES_ENV_OUTPUT_EOF"
          } >> "$GITHUB_ENV"
        done
    - name: Cleanup
      if: always() && steps.run.outcome != 'success'
      shell: bash
      run: rm -rf ./.tmp-dynamic-uses
