name: Set Environment Variables
description: Implementation detail of dynamic-uses, not guaranteed to be stable
inputs:
  variables:
    description: JSON object of variables to set
    required: true
  prefix:
    description: Prefix to use for the environment variable names
    required: false
  upcase:
    description: Whether to capitalize environment variable names
    required: false
  on-conflict:
    description: Error handling behavior when an environment variable conflicts with an existing variable of the same name
    required: true
runs:
  using: node24
  main: dist/main.mjs